### 密码模式
POST http://localhost:63071/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username=super&password=111111

### 校验jwt令牌
POST http://localhost:63071/auth/oauth/check_token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJjcmVhdGVUaW1lXCI6XCIyMDIyLTA5LTI4VDA4OjMyOjAzXCIsXCJpZFwiOlwiNDZcIixcIm5hbWVcIjpcIui2hee6p-euoeeQhuWRmFwiLFwic2V4XCI6XCIxXCIsXCJzdGF0dXNcIjpcIjFcIixcInVzZXJuYW1lXCI6XCJzdXBlclwiLFwidXR5cGVcIjpcIjEwMTAwM1wifSIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2ODI0MzgxODMsImF1dGhvcml0aWVzIjpbInRlc3QiXSwianRpIjoiNDE1MGNkYTUtMTcxMS00OTg0LWE1ZjUtYzJhN2ZhZjRkYjYzIiwiY2xpZW50X2lkIjoiWGNXZWJBcHAifQ.iDBemXfYKUkPpNewj6Arv3G8sNKekIE7Qj9dpy_yAw0

### 授权码模式申请令牌
POST http://localhost:63071/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=authorization_code&code=ebbPBC&redirect_uri=http://www.51xuecheng.cn/

### 通过网关访问资源服务
GET http://localhost:63010/content/course/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJjcmVhdGVUaW1lXCI6XCIyMDIyLTA5LTI4VDA4OjMyOjAzXCIsXCJpZFwiOlwiNDZcIixcIm5hbWVcIjpcIui2hee6p-euoeeQhuWRmFwiLFwic2V4XCI6XCIxXCIsXCJzdGF0dXNcIjpcIjFcIixcInVzZXJuYW1lXCI6XCJzdXBlclwiLFwidXR5cGVcIjpcIjEwMTAwM1wifSIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2ODI0MzgxODMsImF1dGhvcml0aWVzIjpbInRlc3QiXSwianRpIjoiNDE1MGNkYTUtMTcxMS00OTg0LWE1ZjUtYzJhN2ZhZjRkYjYzIiwiY2xpZW50X2lkIjoiWGNXZWJBcHAifQ.iDBemXfYKUkPpNewj6Arv3G8sNKekIE7Qj9dpy_yAw0

### 密码模式 , 请求参数为AuthParamsDto
POST http://localhost:63071/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username={"username":"t1", "password":"111111", "authType":"password"}